# Generated by Django 5.0 on 2025-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='images/testimonial_placeholder.png', null=True, upload_to='testimonials/'),
        ),
    ]
