# Generated by Django 5.0 on 2025-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='blogs/'),
        ),
    ]
